version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dagger
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

